name: Build Windows

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: self-hosted
    env:
      VSCODE_SKIP_NODE_VERSION_CHECK: "1"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'ainative-studio/package-lock.json'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Configure Windows for build
      run: |
        # Add exclusion for build directory to Windows Defender
        try {
          Add-MpPreference -ExclusionPath "$env:GITHUB_WORKSPACE" -ErrorAction SilentlyContinue
          Write-Output "Added Windows Defender exclusion for workspace"
        }
        catch {
          Write-Output "Could not add Windows Defender exclusion (may require admin rights)"
        }
        # Set npm to use shorter paths to avoid Windows path length limits
        npm config set cache "C:\npm-cache" --global
        npm config set prefix "C:\npm-prefix" --global
        
        # Configure git for postinstall script
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global init.defaultBranch main
      shell: powershell
    
    - name: Cache Node modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('ainative-studio/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Cache TypeScript build
      uses: actions/cache@v4
      with:
        path: |
          ainative-studio/out
          ainative-studio/out-build
        key: ${{ runner.os }}-typescript-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-typescript-
    
    - name: Install Node.js dependencies
      working-directory: ainative-studio
      run: |
        # Clear npm cache and remove node_modules if it exists to avoid file locking issues
        npm cache clean --force
        if (Test-Path "node_modules") { Remove-Item -Recurse -Force "node_modules" -ErrorAction SilentlyContinue }
        
        # Try running npm install with verbose output to see what's failing
        Write-Output "Node version: $(node --version)"
        Write-Output "NPM version: $(npm --version)"
        Write-Output "Current directory: $(Get-Location)"
        Write-Output "Files in current directory:"
        Get-ChildItem | Select-Object Name, Length | Format-Table
        
        # Retry npm install up to 3 times to handle Windows file locking
        $attempt = 1
        $maxAttempts = 3
        do {
          Write-Output "Attempt $attempt of $maxAttempts"
          try {
            # Run npm install with detailed output to diagnose issues
            Write-Output "Running npm install..."
            npm install --verbose
            Write-Output "npm install completed successfully"
            break
          }
          catch {
            Write-Output "npm install failed with error: $_"
            if ($attempt -eq $maxAttempts) {
              throw "npm install failed after $maxAttempts attempts: $_"
            }
            Write-Output "Retrying npm install in 10 seconds..."
            Start-Sleep -Seconds 10
            $attempt++
          }
        } while ($attempt -le $maxAttempts)
      shell: powershell
    
    - name: Build React components
      working-directory: ainative-studio
      run: |
        npm run buildreact
      shell: powershell
    
    - name: Compile TypeScript
      working-directory: ainative-studio
      run: |
        # Use increased memory for TypeScript compilation
        $env:NODE_OPTIONS = "--max-old-space-size=16384"
        npm run compile
      shell: powershell
    
    - name: Run tests
      working-directory: ainative-studio
      run: |
        # Run Node tests with increased memory
        $env:NODE_OPTIONS = "--max-old-space-size=8192"
        npm run test-node
        # Run browser tests
        npm run test-browser
      shell: powershell
    
    - name: Build Windows x64 package
      working-directory: ainative-studio
      run: |
        # Build with maximum memory allocation
        $env:NODE_OPTIONS = "--max-old-space-size=16384"
        npm run gulp vscode-win32-x64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: powershell
    
    - name: Create ZIP archive
      run: |
        cd ../VSCode-win32-x64
        Compress-Archive -Path * -DestinationPath ../ainative-studio-win32-x64.zip
      shell: powershell
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: ainative-studio-win32-x64
        path: ../ainative-studio-win32-x64.zip
        retention-days: 30
    
    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ../ainative-studio-win32-x64.zip
        draft: false
        prerelease: contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
